[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/webhook/devi"
  to = "/.netlify/functions/devi-webhook-queue"
  status = 200

[functions.devi-webhook-queue]
  path = "netlify/functions/devi-webhook-queue.js"

[functions.process-devi-queue]
  path = "netlify/functions/process-devi-queue.js"
Cache bust Fri, Oct  2, 2026  6:00:58 PM - force rebuild
